version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: philong-postgres
    environment:
      POSTGRES_DB: philong_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - philong-network

  # Python Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: philong-backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/philong_db
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - philong-network
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: philong-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - philong-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=https://qlns-philong.onrender.com
    command: npm start

volumes:
  postgres_data:

networks:
  philong-network:
    driver: bridge