from fastapi import APIRouter
from typing import List, Dict

router = APIRouter(prefix="/api/options", tags=["options"])

@router.get("/dantoc")
def get_dantoc_options():
    """Get dân tộc options"""
    return [
        {"value": "Kinh", "label": "Kinh"},
        {"value": "Tày", "label": "Tày"},
        {"value": "Thái", "label": "Thái"},
        {"value": "Mường", "label": "Mường"},
        {"value": "Khmer", "label": "Khmer"},
        {"value": "Hoa", "label": "Hoa"},
        {"value": "Nùng", "label": "Nùng"},
        {"value": "H'Mông", "label": "H'Mông"},
        {"value": "Dao", "label": "Dao"},
        {"value": "Gia Rai", "label": "Gia Rai"},
        {"value": "Ê Đê", "label": "Ê Đê"},
        {"value": "Ba Na", "label": "Ba Na"},
        {"value": "Xơ Đăng", "label": "Xơ Đăng"},
        {"value": "Sán Chay", "label": "Sán Chay"},
        {"value": "Cơ Ho", "label": "Cơ Ho"},
        {"value": "Chăm", "label": "Chăm"},
        {"value": "Sán Dìu", "label": "Sán Dìu"},
        {"value": "Hrê", "label": "Hrê"},
        {"value": "Mnông", "label": "Mnông"},
        {"value": "Ra Glai", "label": "Ra Glai"},
        {"value": "Xtiêng", "label": "Xtiêng"},
        {"value": "Bru-Vân Kiều", "label": "Bru-Vân Kiều"},
        {"value": "Thổ", "label": "Thổ"},
        {"value": "Giáy", "label": "Giáy"},
        {"value": "Cơ Tu", "label": "Cơ Tu"},
        {"value": "Gié Triêng", "label": "Gié Triêng"},
        {"value": "Mạ", "label": "Mạ"},
        {"value": "Khơ Mú", "label": "Khơ Mú"},
        {"value": "Co", "label": "Co"},
        {"value": "Tà Ôi", "label": "Tà Ôi"},
        {"value": "Chơ Ro", "label": "Chơ Ro"},
        {"value": "Xinh Mun", "label": "Xinh Mun"},
        {"value": "Hà Nhì", "label": "Hà Nhì"},
        {"value": "Chu Ru", "label": "Chu Ru"},
        {"value": "Lào", "label": "Lào"},
        {"value": "La Chí", "label": "La Chí"},
        {"value": "La Ha", "label": "La Ha"},
        {"value": "Phù Lá", "label": "Phù Lá"},
        {"value": "La Hủ", "label": "La Hủ"},
        {"value": "Lự", "label": "Lự"},
        {"value": "Lô Lô", "label": "Lô Lô"},
        {"value": "Chứt", "label": "Chứt"},
        {"value": "Mảng", "label": "Mảng"},
        {"value": "Pà Thẻn", "label": "Pà Thẻn"},
        {"value": "Cơ Lao", "label": "Cơ Lao"},
        {"value": "Cống", "label": "Cống"},
        {"value": "Bố Y", "label": "Bố Y"},
        {"value": "Si La", "label": "Si La"},
        {"value": "Pu Péo", "label": "Pu Péo"},
        {"value": "Brâu", "label": "Brâu"},
        {"value": "Ơ Đu", "label": "Ơ Đu"},
        {"value": "Rơ Măm", "label": "Rơ Măm"},
        {"value": "Khác", "label": "Khác"}
    ]

@router.get("/suckhoe")
def get_suckhoe_options():
    """Get sức khỏe options"""
    return [
        {"value": "Tốt", "label": "Tốt"},
        {"value": "Khá", "label": "Khá"},
        {"value": "Trung bình", "label": "Trung bình"},
        {"value": "Yếu", "label": "Yếu"},
        {"value": "Có bệnh mãn tính", "label": "Có bệnh mãn tính"},
        {"value": "Khuyết tật", "label": "Khuyết tật"},
        {"value": "Khác", "label": "Khác"}
    ]

@router.get("/quoctich")
def get_quoctich_options():
    """Get quốc tịch options"""
    return [
        {"value": "Việt Nam", "label": "Việt Nam"},
        {"value": "Lào", "label": "Lào"},
        {"value": "Campuchia", "label": "Campuchia"},
        {"value": "Thái Lan", "label": "Thái Lan"},
        {"value": "Myanmar", "label": "Myanmar"},
        {"value": "Malaysia", "label": "Malaysia"},
        {"value": "Indonesia", "label": "Indonesia"},
        {"value": "Philippines", "label": "Philippines"},
        {"value": "Singapore", "label": "Singapore"},
        {"value": "Brunei", "label": "Brunei"},
        {"value": "Trung Quốc", "label": "Trung Quốc"},
        {"value": "Nhật Bản", "label": "Nhật Bản"},
        {"value": "Hàn Quốc", "label": "Hàn Quốc"},
        {"value": "Mông Cổ", "label": "Mông Cổ"},
        {"value": "Ấn Độ", "label": "Ấn Độ"},
        {"value": "Pakistan", "label": "Pakistan"},
        {"value": "Bangladesh", "label": "Bangladesh"},
        {"value": "Sri Lanka", "label": "Sri Lanka"},
        {"value": "Nepal", "label": "Nepal"},
        {"value": "Bhutan", "label": "Bhutan"},
        {"value": "Maldives", "label": "Maldives"},
        {"value": "Afghanistan", "label": "Afghanistan"},
        {"value": "Iran", "label": "Iran"},
        {"value": "Iraq", "label": "Iraq"},
        {"value": "Kuwait", "label": "Kuwait"},
        {"value": "Saudi Arabia", "label": "Saudi Arabia"},
        {"value": "Bahrain", "label": "Bahrain"},
        {"value": "Qatar", "label": "Qatar"},
        {"value": "UAE", "label": "UAE"},
        {"value": "Oman", "label": "Oman"},
        {"value": "Yemen", "label": "Yemen"},
        {"value": "Syria", "label": "Syria"},
        {"value": "Lebanon", "label": "Lebanon"},
        {"value": "Jordan", "label": "Jordan"},
        {"value": "Israel", "label": "Israel"},
        {"value": "Palestine", "label": "Palestine"},
        {"value": "Egypt", "label": "Egypt"},
        {"value": "Libya", "label": "Libya"},
        {"value": "Tunisia", "label": "Tunisia"},
        {"value": "Algeria", "label": "Algeria"},
        {"value": "Morocco", "label": "Morocco"},
        {"value": "Sudan", "label": "Sudan"},
        {"value": "South Sudan", "label": "South Sudan"},
        {"value": "Ethiopia", "label": "Ethiopia"},
        {"value": "Eritrea", "label": "Eritrea"},
        {"value": "Djibouti", "label": "Djibouti"},
        {"value": "Somalia", "label": "Somalia"},
        {"value": "Kenya", "label": "Kenya"},
        {"value": "Uganda", "label": "Uganda"},
        {"value": "Tanzania", "label": "Tanzania"},
        {"value": "Rwanda", "label": "Rwanda"},
        {"value": "Burundi", "label": "Burundi"},
        {"value": "DR Congo", "label": "DR Congo"},
        {"value": "Congo", "label": "Congo"},
        {"value": "Gabon", "label": "Gabon"},
        {"value": "Equatorial Guinea", "label": "Equatorial Guinea"},
        {"value": "São Tomé and Príncipe", "label": "São Tomé and Príncipe"},
        {"value": "Cameroon", "label": "Cameroon"},
        {"value": "Central African Republic", "label": "Central African Republic"},
        {"value": "Chad", "label": "Chad"},
        {"value": "Niger", "label": "Niger"},
        {"value": "Nigeria", "label": "Nigeria"},
        {"value": "Benin", "label": "Benin"},
        {"value": "Togo", "label": "Togo"},
        {"value": "Ghana", "label": "Ghana"},
        {"value": "Côte d'Ivoire", "label": "Côte d'Ivoire"},
        {"value": "Liberia", "label": "Liberia"},
        {"value": "Sierra Leone", "label": "Sierra Leone"},
        {"value": "Guinea", "label": "Guinea"},
        {"value": "Guinea-Bissau", "label": "Guinea-Bissau"},
        {"value": "Senegal", "label": "Senegal"},
        {"value": "The Gambia", "label": "The Gambia"},
        {"value": "Mali", "label": "Mali"},
        {"value": "Burkina Faso", "label": "Burkina Faso"},
        {"value": "Cape Verde", "label": "Cape Verde"},
        {"value": "Mauritania", "label": "Mauritania"},
        {"value": "Western Sahara", "label": "Western Sahara"},
        {"value": "Angola", "label": "Angola"},
        {"value": "Zambia", "label": "Zambia"},
        {"value": "Zimbabwe", "label": "Zimbabwe"},
        {"value": "Botswana", "label": "Botswana"},
        {"value": "Namibia", "label": "Namibia"},
        {"value": "South Africa", "label": "South Africa"},
        {"value": "Lesotho", "label": "Lesotho"},
        {"value": "Eswatini", "label": "Eswatini"},
        {"value": "Madagascar", "label": "Madagascar"},
        {"value": "Comoros", "label": "Comoros"},
        {"value": "Mauritius", "label": "Mauritius"},
        {"value": "Seychelles", "label": "Seychelles"},
        {"value": "Mozambique", "label": "Mozambique"},
        {"value": "Malawi", "label": "Malawi"},
        {"value": "Russia", "label": "Russia"},
        {"value": "Ukraine", "label": "Ukraine"},
        {"value": "Belarus", "label": "Belarus"},
        {"value": "Moldova", "label": "Moldova"},
        {"value": "Romania", "label": "Romania"},
        {"value": "Bulgaria", "label": "Bulgaria"},
        {"value": "Serbia", "label": "Serbia"},
        {"value": "Montenegro", "label": "Montenegro"},
        {"value": "Bosnia and Herzegovina", "label": "Bosnia and Herzegovina"},
        {"value": "Croatia", "label": "Croatia"},
        {"value": "Slovenia", "label": "Slovenia"},
        {"value": "North Macedonia", "label": "North Macedonia"},
        {"value": "Albania", "label": "Albania"},
        {"value": "Kosovo", "label": "Kosovo"},
        {"value": "Greece", "label": "Greece"},
        {"value": "Turkey", "label": "Turkey"},
        {"value": "Cyprus", "label": "Cyprus"},
        {"value": "Georgia", "label": "Georgia"},
        {"value": "Armenia", "label": "Armenia"},
        {"value": "Azerbaijan", "label": "Azerbaijan"},
        {"value": "Kazakhstan", "label": "Kazakhstan"},
        {"value": "Uzbekistan", "label": "Uzbekistan"},
        {"value": "Turkmenistan", "label": "Turkmenistan"},
        {"value": "Kyrgyzstan", "label": "Kyrgyzstan"},
        {"value": "Tajikistan", "label": "Tajikistan"},
        {"value": "Afghanistan", "label": "Afghanistan"},
        {"value": "Poland", "label": "Poland"},
        {"value": "Czech Republic", "label": "Czech Republic"},
        {"value": "Slovakia", "label": "Slovakia"},
        {"value": "Hungary", "label": "Hungary"},
        {"value": "Austria", "label": "Austria"},
        {"value": "Germany", "label": "Germany"},
        {"value": "Switzerland", "label": "Switzerland"},
        {"value": "Liechtenstein", "label": "Liechtenstein"},
        {"value": "France", "label": "France"},
        {"value": "Monaco", "label": "Monaco"},
        {"value": "Italy", "label": "Italy"},
        {"value": "San Marino", "label": "San Marino"},
        {"value": "Vatican City", "label": "Vatican City"},
        {"value": "Spain", "label": "Spain"},
        {"value": "Portugal", "label": "Portugal"},
        {"value": "Andorra", "label": "Andorra"},
        {"value": "Netherlands", "label": "Netherlands"},
        {"value": "Belgium", "label": "Belgium"},
        {"value": "Luxembourg", "label": "Luxembourg"},
        {"value": "United Kingdom", "label": "United Kingdom"},
        {"value": "Ireland", "label": "Ireland"},
        {"value": "Iceland", "label": "Iceland"},
        {"value": "Denmark", "label": "Denmark"},
        {"value": "Norway", "label": "Norway"},
        {"value": "Sweden", "label": "Sweden"},
        {"value": "Finland", "label": "Finland"},
        {"value": "Estonia", "label": "Estonia"},
        {"value": "Latvia", "label": "Latvia"},
        {"value": "Lithuania", "label": "Lithuania"},
        {"value": "Canada", "label": "Canada"},
        {"value": "United States", "label": "United States"},
        {"value": "Mexico", "label": "Mexico"},
        {"value": "Guatemala", "label": "Guatemala"},
        {"value": "Belize", "label": "Belize"},
        {"value": "El Salvador", "label": "El Salvador"},
        {"value": "Honduras", "label": "Honduras"},
        {"value": "Nicaragua", "label": "Nicaragua"},
        {"value": "Costa Rica", "label": "Costa Rica"},
        {"value": "Panama", "label": "Panama"},
        {"value": "Cuba", "label": "Cuba"},
        {"value": "Jamaica", "label": "Jamaica"},
        {"value": "Haiti", "label": "Haiti"},
        {"value": "Dominican Republic", "label": "Dominican Republic"},
        {"value": "Puerto Rico", "label": "Puerto Rico"},
        {"value": "Trinidad and Tobago", "label": "Trinidad and Tobago"},
        {"value": "Barbados", "label": "Barbados"},
        {"value": "Grenada", "label": "Grenada"},
        {"value": "Saint Vincent and the Grenadines", "label": "Saint Vincent and the Grenadines"},
        {"value": "Saint Lucia", "label": "Saint Lucia"},
        {"value": "Dominica", "label": "Dominica"},
        {"value": "Antigua and Barbuda", "label": "Antigua and Barbuda"},
        {"value": "Saint Kitts and Nevis", "label": "Saint Kitts and Nevis"},
        {"value": "Bahamas", "label": "Bahamas"},
        {"value": "Brazil", "label": "Brazil"},
        {"value": "Argentina", "label": "Argentina"},
        {"value": "Chile", "label": "Chile"},
        {"value": "Peru", "label": "Peru"},
        {"value": "Colombia", "label": "Colombia"},
        {"value": "Venezuela", "label": "Venezuela"},
        {"value": "Ecuador", "label": "Ecuador"},
        {"value": "Bolivia", "label": "Bolivia"},
        {"value": "Paraguay", "label": "Paraguay"},
        {"value": "Uruguay", "label": "Uruguay"},
        {"value": "Guyana", "label": "Guyana"},
        {"value": "Suriname", "label": "Suriname"},
        {"value": "French Guiana", "label": "French Guiana"},
        {"value": "Falkland Islands", "label": "Falkland Islands"},
        {"value": "Australia", "label": "Australia"},
        {"value": "New Zealand", "label": "New Zealand"},
        {"value": "Papua New Guinea", "label": "Papua New Guinea"},
        {"value": "Fiji", "label": "Fiji"},
        {"value": "Solomon Islands", "label": "Solomon Islands"},
        {"value": "Vanuatu", "label": "Vanuatu"},
        {"value": "New Caledonia", "label": "New Caledonia"},
        {"value": "Kiribati", "label": "Kiribati"},
        {"value": "Tuvalu", "label": "Tuvalu"},
        {"value": "Nauru", "label": "Nauru"},
        {"value": "Marshall Islands", "label": "Marshall Islands"},
        {"value": "Micronesia", "label": "Micronesia"},
        {"value": "Palau", "label": "Palau"},
        {"value": "Samoa", "label": "Samoa"},
        {"value": "Tonga", "label": "Tonga"},
        {"value": "Cook Islands", "label": "Cook Islands"},
        {"value": "Niue", "label": "Niue"},
        {"value": "Tokelau", "label": "Tokelau"},
        {"value": "American Samoa", "label": "American Samoa"},
        {"value": "Guam", "label": "Guam"},
        {"value": "Northern Mariana Islands", "label": "Northern Mariana Islands"},
        {"value": "Hawaii", "label": "Hawaii"},
        {"value": "Khác", "label": "Khác"}
    ] 